mkdir -p tools/spaceworld

cat > tools/spaceworld/reimport_spaceworld_all.sh <<'BASH'
#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Spaceworld Mass Import Script (Authoritative)
# ============================================================
#
# What it DOES (today):
#   [A] Reconvert Spaceworld ICONS from ref GIFs -> 32x64 .4bpp (2 frames stacked)
#   [B] Validate icon output (.4bpp must be 1024 bytes each)
#   [C] Regenerate gSwIcon_* declarations and inject into include/graphics.h
#
# What it intentionally does NOT do automatically (yet):
#   - engine limit patches
#   - vanilla mon edits
#   - guessing move IDs
#   - "make clean" / full rebuild steps
#
# Usage:
#   bash tools/spaceworld/reimport_spaceworld_all.sh /path/to/spaceworld_root
#
# Dry-run vs Apply:
#   DRY-RUN default.
#   Add --apply as 2nd arg to actually write icons + modify include/graphics.h
#
# Example:
#   bash tools/spaceworld/reimport_spaceworld_all.sh ~/spaceworld_disasm --apply
# ============================================================

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "Usage: $0 /path/to/spaceworld_root [--apply]"
  exit 1
fi

SPACEWORLD_ROOT="$(realpath "$1")"
APPLY="${2:-}"

REPO_ROOT="$(pwd)"

MODE="DRY-RUN"
if [[ "$APPLY" == "--apply" ]]; then
  MODE="APPLY"
fi

echo "== Spaceworld root: $SPACEWORLD_ROOT"
echo "== Repo root:       $REPO_ROOT"
echo "== Mode:            $MODE"

# ------------------------------------------------------------
# Config (override via environment variables if you want)
# ------------------------------------------------------------
GIFDIR="${GIFDIR:-$REPO_ROOT/graphics/spaceworld/ref_gifs}"
ICON_OUTDIR="${ICON_OUTDIR:-$REPO_ROOT/graphics/spaceworld/icons}"
ICON_PAL="${ICON_PAL:-$REPO_ROOT/graphics/pokemon/icon_palettes/spaceworld_icon_pal6.gbapal}"

GRAPHICS_H="${GRAPHICS_H:-$REPO_ROOT/include/graphics.h}"

# Ensure required paths exist
req() { [[ -e "$1" ]] || { echo "ERROR: Missing required path: $1" ; exit 2; }; }

req "$SPACEWORLD_ROOT"
req "$GIFDIR"
req "$ICON_PAL"
req "$REPO_ROOT/tools/convert_spaceworld_gifs_strict.py"
req "$GRAPHICS_H"

mkdir -p "$ICON_OUTDIR"

# ------------------------------------------------------------
# [A] ICONS: GIF -> 32x64 .4bpp (two frames stacked)
# ------------------------------------------------------------
echo
echo "== [A] ICON reconversion (GIF -> .4bpp 32x64) =="
echo "GIFDIR:     $GIFDIR"
echo "OUTDIR:     $ICON_OUTDIR"
echo "PALETTE:    $ICON_PAL"

if [[ "$MODE" == "DRY-RUN" ]]; then
  python3 "$REPO_ROOT/tools/convert_spaceworld_gifs_strict.py" \
    --gifdir "$GIFDIR" \
    --outdir "$ICON_OUTDIR" \
    --gbapal "$ICON_PAL"
else
  python3 "$REPO_ROOT/tools/convert_spaceworld_gifs_strict.py" \
    --gifdir "$GIFDIR" \
    --outdir "$ICON_OUTDIR" \
    --gbapal "$ICON_PAL" \
    --apply
fi

# ------------------------------------------------------------
# [B] Sanity-check icon output sizes
# ------------------------------------------------------------
echo
echo "== [B] ICON sanity check (.4bpp must be 1024 bytes) =="

bad_count=0
total_count=0

shopt -s nullglob
for f in "$ICON_OUTDIR"/*.4bpp; do
  ((total_count++)) || true
  sz="$(stat -c%s "$f")"
  if [[ "$sz" -ne 1024 ]]; then
    echo "BAD SIZE: $(basename "$f") = $sz bytes (expected 1024)"
    ((bad_count++)) || true
  fi
done
shopt -u nullglob

echo "Icon files found: $total_count"
if [[ "$total_count" -eq 0 ]]; then
  echo "ERROR: No .4bpp icons found in $ICON_OUTDIR"
  exit 3
fi
if [[ "$bad_count" -ne 0 ]]; then
  echo "ERROR: $bad_count icon(s) have wrong size. Aborting."
  exit 4
fi
echo "OK: all icons are 1024 bytes"

# ------------------------------------------------------------
# [C] Generate gSwIcon_* declarations and inject into graphics.h
# ------------------------------------------------------------
echo
echo "== [C] Generating + injecting gSwIcon_* declarations into include/graphics.h =="

# We generate a temporary header snippet with extern declarations.
TMP_SNIP="$(mktemp)"
python3 - <<'PY' > "$TMP_SNIP"
import os, re
from pathlib import Path

icons_dir = Path(os.environ.get("ICON_OUTDIR", "graphics/spaceworld/icons"))
files = sorted(icons_dir.glob("*.4bpp"))

def to_symbol(stem: str) -> str:
    # file stem like "ho_oh" -> "HoOh"; "mr_mime" -> "MrMime"
    parts = re.split(r"[^A-Za-z0-9]+", stem.strip())
    parts = [p for p in parts if p]
    return "".join(p[:1].upper() + p[1:] for p in parts)

print("// AUTOGENERATED: Spaceworld icon externs")
print("// Source: graphics/spaceworld/icons/*.4bpp")
print("// Each icon is 32x64 (2 frames stacked), 4bpp tiled => 1024 bytes\n")

for p in files:
    sym = to_symbol(p.stem)
    print(f"extern const u8 gSwIcon_{sym}[];")
PY

# Now inject/replace into include/graphics.h between markers.
BEGIN_MARK='// === SPACEWORLD ICONS: AUTOGEN BEGIN ==='
END_MARK='// === SPACEWORLD ICONS: AUTOGEN END ==='

if [[ "$MODE" == "DRY-RUN" ]]; then
  echo
  echo "DRY-RUN: Would update $GRAPHICS_H between markers:"
  echo "  $BEGIN_MARK"
  echo "  $END_MARK"
  echo
  echo "Preview of generated declarations (first 20 lines):"
  head -n 20 "$TMP_SNIP"
  echo "..."
else
  # If markers don't exist, append them to the end of the file.
  if ! grep -qF "$BEGIN_MARK" "$GRAPHICS_H"; then
    echo >> "$GRAPHICS_H"
    echo "$BEGIN_MARK" >> "$GRAPHICS_H"
    echo "$END_MARK" >> "$GRAPHICS_H"
  fi

  # Replace everything between the markers (inclusive interior) with our snippet.
  # We preserve the markers themselves.
  perl -0777 -i -pe '
    my $begin = quotemeta($ENV{BEGIN_MARK});
    my $end   = quotemeta($ENV{END_MARK});
    my $ins   = do { local(@ARGV,$/) = ($ENV{TMP_SNIP}); <> };
    s/($begin\n).*?(\n$end)/$1$ins$2/s
  ' "$GRAPHICS_H"

  echo "Updated: $GRAPHICS_H"
fi

rm -f "$TMP_SNIP"

# ------------------------------------------------------------
# [D] (Optional) Your other Spaceworld import steps can go here
# ------------------------------------------------------------
echo
echo "== [D] (Optional) Spaceworld sprites/stats/dex/etc =="
echo "NOTE: Not executed automatically here because your repo has multiple scripts."
echo "Add your calls below once you confirm which ones are authoritative in your pipeline."
echo
echo "For reference, you currently have:"
echo "  tools/spaceworld/import_spaceworld_sprites.py"
echo "  tools/spaceworld/gen_spaceworld_pokemon_gfx.py"
echo "  tools/spaceworld/patch_spaceworld_sprites.py"
echo "  tools/spaceworld/patch_spaceworld_pic_sizes.py"
echo "  tools/spaceworld/patch_spaceworld_icons.py"
echo
echo "Done."

BASH

chmod +x tools/spaceworld/reimport_spaceworld_all.sh
echo "Wrote tools/spaceworld/reimport_spaceworld_all.sh"
