// Auto-generated. Do not edit.
#include "global.h"
#include "constants/species_bw3g.h"

static const u8 sBw3gSpeciesName_SNIVY[] = _("SNIVY");
static const u8 sBw3gSpeciesName_SERVINE[] = _("SERVINE");
static const u8 sBw3gSpeciesName_SERPERIOR[] = _("SERPERIOR");
static const u8 sBw3gSpeciesName_TEPIG[] = _("TEPIG");
static const u8 sBw3gSpeciesName_PIGNITE[] = _("PIGNITE");
static const u8 sBw3gSpeciesName_EMBOAR[] = _("EMBOAR");
static const u8 sBw3gSpeciesName_OSHAWOTT[] = _("OSHAWOTT");
static const u8 sBw3gSpeciesName_DEWOTT[] = _("DEWOTT");
static const u8 sBw3gSpeciesName_SAMUROTT[] = _("SAMUROTT");
static const u8 sBw3gSpeciesName_PATRAT[] = _("PATRAT");
static const u8 sBw3gSpeciesName_WATCHOG[] = _("WATCHOG");
static const u8 sBw3gSpeciesName_PURRLOIN[] = _("PURRLOIN");
static const u8 sBw3gSpeciesName_LIEPARD[] = _("LIEPARD");
static const u8 sBw3gSpeciesName_PIDOVE[] = _("PIDOVE");
static const u8 sBw3gSpeciesName_TRANQUILL[] = _("TRANQUILL");
static const u8 sBw3gSpeciesName_UNFEZANT[] = _("UNFEZANT");
static const u8 sBw3gSpeciesName_IGGLYBUFF[] = _("IGGLYBUFF");
static const u8 sBw3gSpeciesName_JIGGLYPUFF[] = _("JIGGLYPUFF");
static const u8 sBw3gSpeciesName_WIGGLYTUFF[] = _("WIGGLYTUFF");
static const u8 sBw3gSpeciesName_AZURILL[] = _("AZURILL");
static const u8 sBw3gSpeciesName_MARILL[] = _("MARILL");
static const u8 sBw3gSpeciesName_AZUMARILL[] = _("AZUMARILL");
static const u8 sBw3gSpeciesName_SEWADDLE[] = _("SEWADDLE");
static const u8 sBw3gSpeciesName_SWADLOON[] = _("SWADLOON");
static const u8 sBw3gSpeciesName_LEAVANNY[] = _("LEAVANNY");
static const u8 sBw3gSpeciesName_VENIPEDE[] = _("VENIPEDE");
static const u8 sBw3gSpeciesName_WHIRLIPEDE[] = _("WHIRLIPEDE");
static const u8 sBw3gSpeciesName_SCOLIPEDE[] = _("SCOLIPEDE");
static const u8 sBw3gSpeciesName_LILLIPUP[] = _("LILLIPUP");
static const u8 sBw3gSpeciesName_HERDIER[] = _("HERDIER");
static const u8 sBw3gSpeciesName_STOUTLAND[] = _("STOUTLAND");
static const u8 sBw3gSpeciesName_TYMPOLE[] = _("TYMPOLE");
static const u8 sBw3gSpeciesName_PALPITOAD[] = _("PALPITOAD");
static const u8 sBw3gSpeciesName_SEISMITOAD[] = _("SEISMITOAD");
static const u8 sBw3gSpeciesName_ZUBAT[] = _("ZUBAT");
static const u8 sBw3gSpeciesName_GOLBAT[] = _("GOLBAT");
static const u8 sBw3gSpeciesName_CROBAT[] = _("CROBAT");
static const u8 sBw3gSpeciesName_WOOBAT[] = _("WOOBAT");
static const u8 sBw3gSpeciesName_SWOOBAT[] = _("SWOOBAT");
static const u8 sBw3gSpeciesName_ROGGENROLA[] = _("ROGGENROLA");
static const u8 sBw3gSpeciesName_BOLDORE[] = _("BOLDORE");
static const u8 sBw3gSpeciesName_GIGALITH[] = _("GIGALITH");
static const u8 sBw3gSpeciesName_CLEFFA[] = _("CLEFFA");
static const u8 sBw3gSpeciesName_CLEFAIRY[] = _("CLEFAIRY");
static const u8 sBw3gSpeciesName_CLEFABLE[] = _("CLEFABLE");
static const u8 sBw3gSpeciesName_MUNNA[] = _("MUNNA");
static const u8 sBw3gSpeciesName_MUSHARNA[] = _("MUSHARNA");
static const u8 sBw3gSpeciesName_RUFFLET[] = _("RUFFLET");
static const u8 sBw3gSpeciesName_BRAVIARY[] = _("BRAVIARY");
static const u8 sBw3gSpeciesName_VULLABY[] = _("VULLABY");
static const u8 sBw3gSpeciesName_MANDIBUZZ[] = _("MANDIBUZZ");
static const u8 sBw3gSpeciesName_BUDEW[] = _("BUDEW");
static const u8 sBw3gSpeciesName_ROSELIA[] = _("ROSELIA");
static const u8 sBw3gSpeciesName_ROSERADE[] = _("ROSERADE");
static const u8 sBw3gSpeciesName_FOONGUS[] = _("FOONGUS");
static const u8 sBw3gSpeciesName_AMOONGUSS[] = _("AMOONGUSS");
static const u8 sBw3gSpeciesName_RALTS[] = _("RALTS");
static const u8 sBw3gSpeciesName_KIRLIA[] = _("KIRLIA");
static const u8 sBw3gSpeciesName_GARDEVOIR[] = _("GARDEVOIR");
static const u8 sBw3gSpeciesName_GALLADE[] = _("GALLADE");
static const u8 sBw3gSpeciesName_BLITZLE[] = _("BLITZLE");
static const u8 sBw3gSpeciesName_ZEBSTRIKA[] = _("ZEBSTRIKA");
static const u8 sBw3gSpeciesName_MAREEP[] = _("MAREEP");
static const u8 sBw3gSpeciesName_FLAAFFY[] = _("FLAAFFY");
static const u8 sBw3gSpeciesName_AMPHAROS[] = _("AMPHAROS");
static const u8 sBw3gSpeciesName_DRILBUR[] = _("DRILBUR");
static const u8 sBw3gSpeciesName_EXCADRILL[] = _("EXCADRILL");
static const u8 sBw3gSpeciesName_SNUBBULL[] = _("SNUBBULL");
static const u8 sBw3gSpeciesName_GRANBULL[] = _("GRANBULL");
static const u8 sBw3gSpeciesName_RIOLU[] = _("RIOLU");
static const u8 sBw3gSpeciesName_LUCARIO[] = _("LUCARIO");
static const u8 sBw3gSpeciesName_TIMBURR[] = _("TIMBURR");
static const u8 sBw3gSpeciesName_GURDURR[] = _("GURDURR");
static const u8 sBw3gSpeciesName_CONKELDURR[] = _("CONKELDURR");
static const u8 sBw3gSpeciesName_ARON[] = _("ARON");
static const u8 sBw3gSpeciesName_LAIRON[] = _("LAIRON");
static const u8 sBw3gSpeciesName_AGGRON[] = _("AGGRON");
static const u8 sBw3gSpeciesName_ONIX[] = _("ONIX");
static const u8 sBw3gSpeciesName_STEELIX[] = _("STEELIX");
static const u8 sBw3gSpeciesName_NOSEPASS[] = _("NOSEPASS");
static const u8 sBw3gSpeciesName_PROBOPASS[] = _("PROBOPASS");
static const u8 sBw3gSpeciesName_MAWILE[] = _("MAWILE");
static const u8 sBw3gSpeciesName_DWEBBLE[] = _("DWEBBLE");
static const u8 sBw3gSpeciesName_CRUSTLE[] = _("CRUSTLE");
static const u8 sBw3gSpeciesName_DRIFLOON[] = _("DRIFLOON");
static const u8 sBw3gSpeciesName_DRIFBLIM[] = _("DRIFBLIM");
static const u8 sBw3gSpeciesName_MEDITITE[] = _("MEDITITE");
static const u8 sBw3gSpeciesName_MEDICHAM[] = _("MEDICHAM");
static const u8 sBw3gSpeciesName_HOUNDOUR[] = _("HOUNDOUR");
static const u8 sBw3gSpeciesName_HOUNDOOM[] = _("HOUNDOOM");
static const u8 sBw3gSpeciesName_YAMASK[] = _("YAMASK");
static const u8 sBw3gSpeciesName_COFAGRIGUS[] = _("COFAGRIGUS");
static const u8 sBw3gSpeciesName_GASTLY[] = _("GASTLY");
static const u8 sBw3gSpeciesName_HAUNTER[] = _("HAUNTER");
static const u8 sBw3gSpeciesName_GENGAR[] = _("GENGAR");
static const u8 sBw3gSpeciesName_LITWICK[] = _("LITWICK");
static const u8 sBw3gSpeciesName_LAMPENT[] = _("LAMPENT");
static const u8 sBw3gSpeciesName_CHANDELURE[] = _("CHANDELURE");
static const u8 sBw3gSpeciesName_COTTONEE[] = _("COTTONEE");
static const u8 sBw3gSpeciesName_WHIMSICOTT[] = _("WHIMSICOTT");
static const u8 sBw3gSpeciesName_PETILIL[] = _("PETILIL");
static const u8 sBw3gSpeciesName_LILLIGANT[] = _("LILLIGANT");
static const u8 sBw3gSpeciesName_YANMA[] = _("YANMA");
static const u8 sBw3gSpeciesName_YANMEGA[] = _("YANMEGA");
static const u8 sBw3gSpeciesName_SHROOMISH[] = _("SHROOMISH");
static const u8 sBw3gSpeciesName_BRELOOM[] = _("BRELOOM");
static const u8 sBw3gSpeciesName_JOLTIK[] = _("JOLTIK");
static const u8 sBw3gSpeciesName_GALVANTULA[] = _("GALVANTULA");
static const u8 sBw3gSpeciesName_SPIRITOMB[] = _("SPIRITOMB");
static const u8 sBw3gSpeciesName_ZORUA[] = _("ZORUA");
static const u8 sBw3gSpeciesName_ZOROARK[] = _("ZOROARK");
static const u8 sBw3gSpeciesName_TRUBBISH[] = _("TRUBBISH");
static const u8 sBw3gSpeciesName_GARBODOR[] = _("GARBODOR");
static const u8 sBw3gSpeciesName_MAGNEMITE[] = _("MAGNEMITE");
static const u8 sBw3gSpeciesName_MAGNETON[] = _("MAGNETON");
static const u8 sBw3gSpeciesName_MAGNEZONE[] = _("MAGNEZONE");
static const u8 sBw3gSpeciesName_GOTHITA[] = _("GOTHITA");
static const u8 sBw3gSpeciesName_GOTHORITA[] = _("GOTHORITA");
static const u8 sBw3gSpeciesName_GOTHITELLE[] = _("GOTHITELLE");
static const u8 sBw3gSpeciesName_SOLOSIS[] = _("SOLOSIS");
static const u8 sBw3gSpeciesName_DUOSION[] = _("DUOSION");
static const u8 sBw3gSpeciesName_REUNICLUS[] = _("REUNICLUS");
static const u8 sBw3gSpeciesName_DEERLING[] = _("DEERLING");
static const u8 sBw3gSpeciesName_SAWSBUCK[] = _("SAWSBUCK");
static const u8 sBw3gSpeciesName_KARRABLAST[] = _("KARRABLAST");
static const u8 sBw3gSpeciesName_ESCAVALIER[] = _("ESCAVALIER");
static const u8 sBw3gSpeciesName_SHELMET[] = _("SHELMET");
static const u8 sBw3gSpeciesName_ACCELGOR[] = _("ACCELGOR");
static const u8 sBw3gSpeciesName_FERROSEED[] = _("FERROSEED");
static const u8 sBw3gSpeciesName_FERROTHORN[] = _("FERROTHORN");
static const u8 sBw3gSpeciesName_BASCULIN[] = _("BASCULIN");
static const u8 sBw3gSpeciesName_REMORAID[] = _("REMORAID");
static const u8 sBw3gSpeciesName_OCTILLERY[] = _("OCTILLERY");
static const u8 sBw3gSpeciesName_DARUMAKA[] = _("DARUMAKA");
static const u8 sBw3gSpeciesName_DARMANITAN[] = _("DARMANITAN");
static const u8 sBw3gSpeciesName_ELEKID[] = _("ELEKID");
static const u8 sBw3gSpeciesName_ELECTABUZZ[] = _("ELECTABUZZ");
static const u8 sBw3gSpeciesName_ELECTIVIRE[] = _("ELECTIVIRE");
static const u8 sBw3gSpeciesName_MAGBY[] = _("MAGBY");
static const u8 sBw3gSpeciesName_MAGMAR[] = _("MAGMAR");
static const u8 sBw3gSpeciesName_MAGMORTAR[] = _("MAGMORTAR");
static const u8 sBw3gSpeciesName_SANDILE[] = _("SANDILE");
static const u8 sBw3gSpeciesName_KROKOROK[] = _("KROKOROK");
static const u8 sBw3gSpeciesName_KROOKODILE[] = _("KROOKODILE");
static const u8 sBw3gSpeciesName_SKORUPI[] = _("SKORUPI");
static const u8 sBw3gSpeciesName_DRAPION[] = _("DRAPION");
static const u8 sBw3gSpeciesName_TRAPINCH[] = _("TRAPINCH");
static const u8 sBw3gSpeciesName_VIBRAVA[] = _("VIBRAVA");
static const u8 sBw3gSpeciesName_FLYGON[] = _("FLYGON");
static const u8 sBw3gSpeciesName_SCRAGGY[] = _("SCRAGGY");
static const u8 sBw3gSpeciesName_SCRAFTY[] = _("SCRAFTY");
static const u8 sBw3gSpeciesName_NUMEL[] = _("NUMEL");
static const u8 sBw3gSpeciesName_CAMERUPT[] = _("CAMERUPT");
static const u8 sBw3gSpeciesName_MARACTUS[] = _("MARACTUS");
static const u8 sBw3gSpeciesName_GLIGAR[] = _("GLIGAR");
static const u8 sBw3gSpeciesName_GLISCOR[] = _("GLISCOR");
static const u8 sBw3gSpeciesName_BALTOY[] = _("BALTOY");
static const u8 sBw3gSpeciesName_CLAYDOL[] = _("CLAYDOL");
static const u8 sBw3gSpeciesName_SIGILYPH[] = _("SIGILYPH");
static const u8 sBw3gSpeciesName_GOLETT[] = _("GOLETT");
static const u8 sBw3gSpeciesName_GOLURK[] = _("GOLURK");
static const u8 sBw3gSpeciesName_TIRTOUGA[] = _("TIRTOUGA");
static const u8 sBw3gSpeciesName_CARRACOSTA[] = _("CARRACOSTA");
static const u8 sBw3gSpeciesName_ARCHEN[] = _("ARCHEN");
static const u8 sBw3gSpeciesName_ARCHEOPS[] = _("ARCHEOPS");
static const u8 sBw3gSpeciesName_FRILLISH[] = _("FRILLISH");
static const u8 sBw3gSpeciesName_JELLICENT[] = _("JELLICENT");
static const u8 sBw3gSpeciesName_EMOLGA[] = _("EMOLGA");
static const u8 sBw3gSpeciesName_VULPIX[] = _("VULPIX");
static const u8 sBw3gSpeciesName_NINETALES[] = _("NINETALES");
static const u8 sBw3gSpeciesName_DUCKLETT[] = _("DUCKLETT");
static const u8 sBw3gSpeciesName_SWANNA[] = _("SWANNA");
static const u8 sBw3gSpeciesName_SWABLU[] = _("SWABLU");
static const u8 sBw3gSpeciesName_ALTARIA[] = _("ALTARIA");
static const u8 sBw3gSpeciesName_AUDINO[] = _("AUDINO");
static const u8 sBw3gSpeciesName_EEVEE[] = _("EEVEE");
static const u8 sBw3gSpeciesName_VAPOREON[] = _("VAPOREON");
static const u8 sBw3gSpeciesName_JOLTEON[] = _("JOLTEON");
static const u8 sBw3gSpeciesName_FLAREON[] = _("FLAREON");
static const u8 sBw3gSpeciesName_ESPEON[] = _("ESPEON");
static const u8 sBw3gSpeciesName_UMBREON[] = _("UMBREON");
static const u8 sBw3gSpeciesName_LEAFEON[] = _("LEAFEON");
static const u8 sBw3gSpeciesName_GLACEON[] = _("GLACEON");
static const u8 sBw3gSpeciesName_SYLVEON[] = _("SYLVEON");
static const u8 sBw3gSpeciesName_CROAGUNK[] = _("CROAGUNK");
static const u8 sBw3gSpeciesName_TOXICROAK[] = _("TOXICROAK");
static const u8 sBw3gSpeciesName_HEATMOR[] = _("HEATMOR");
static const u8 sBw3gSpeciesName_DURANT[] = _("DURANT");
static const u8 sBw3gSpeciesName_KOFFING[] = _("KOFFING");
static const u8 sBw3gSpeciesName_WEEZING[] = _("WEEZING");
static const u8 sBw3gSpeciesName_CORSOLA[] = _("CORSOLA");
static const u8 sBw3gSpeciesName_PINSIR[] = _("PINSIR");
static const u8 sBw3gSpeciesName_HERACROSS[] = _("HERACROSS");
static const u8 sBw3gSpeciesName_THROH[] = _("THROH");
static const u8 sBw3gSpeciesName_SAWK[] = _("SAWK");
static const u8 sBw3gSpeciesName_TROPIUS[] = _("TROPIUS");
static const u8 sBw3gSpeciesName_PAWNIARD[] = _("PAWNIARD");
static const u8 sBw3gSpeciesName_BISHARP[] = _("BISHARP");
static const u8 sBw3gSpeciesName_SKARMORY[] = _("SKARMORY");
static const u8 sBw3gSpeciesName_MANTYKE[] = _("MANTYKE");
static const u8 sBw3gSpeciesName_MANTINE[] = _("MANTINE");
static const u8 sBw3gSpeciesName_AXEW[] = _("AXEW");
static const u8 sBw3gSpeciesName_FRAXURE[] = _("FRAXURE");
static const u8 sBw3gSpeciesName_HAXORUS[] = _("HAXORUS");
static const u8 sBw3gSpeciesName_BOUFFALANT[] = _("BOUFFALANT");
static const u8 sBw3gSpeciesName_KLINK[] = _("KLINK");
static const u8 sBw3gSpeciesName_KLANG[] = _("KLANG");
static const u8 sBw3gSpeciesName_KLINKLANG[] = _("KLINKLANG");
static const u8 sBw3gSpeciesName_DITTO[] = _("DITTO");
static const u8 sBw3gSpeciesName_STARYU[] = _("STARYU");
static const u8 sBw3gSpeciesName_STARMIE[] = _("STARMIE");
static const u8 sBw3gSpeciesName_CUBCHOO[] = _("CUBCHOO");
static const u8 sBw3gSpeciesName_BEARTIC[] = _("BEARTIC");
static const u8 sBw3gSpeciesName_VANILLITE[] = _("VANILLITE");
static const u8 sBw3gSpeciesName_VANILLISH[] = _("VANILLISH");
static const u8 sBw3gSpeciesName_VANILLUXE[] = _("VANILLUXE");
static const u8 sBw3gSpeciesName_SNEASEL[] = _("SNEASEL");
static const u8 sBw3gSpeciesName_WEAVILE[] = _("WEAVILE");
static const u8 sBw3gSpeciesName_CORPHISH[] = _("CORPHISH");
static const u8 sBw3gSpeciesName_CRAWDAUNT[] = _("CRAWDAUNT");
static const u8 sBw3gSpeciesName_SWINUB[] = _("SWINUB");
static const u8 sBw3gSpeciesName_PILOSWINE[] = _("PILOSWINE");
static const u8 sBw3gSpeciesName_MAMOSWINE[] = _("MAMOSWINE");
static const u8 sBw3gSpeciesName_LARVITAR[] = _("LARVITAR");
static const u8 sBw3gSpeciesName_PUPITAR[] = _("PUPITAR");
static const u8 sBw3gSpeciesName_TYRANITAR[] = _("TYRANITAR");
static const u8 sBw3gSpeciesName_LARVESTA[] = _("LARVESTA");
static const u8 sBw3gSpeciesName_VOLCARONA[] = _("VOLCARONA");
static const u8 sBw3gSpeciesName_TYNAMO[] = _("TYNAMO");
static const u8 sBw3gSpeciesName_EELEKTRIK[] = _("EELEKTRIK");
static const u8 sBw3gSpeciesName_EELEKTROSS[] = _("EELEKTROSS");
static const u8 sBw3gSpeciesName_BELDUM[] = _("BELDUM");
static const u8 sBw3gSpeciesName_METANG[] = _("METANG");
static const u8 sBw3gSpeciesName_METAGROSS[] = _("METAGROSS");
static const u8 sBw3gSpeciesName_SPHEAL[] = _("SPHEAL");
static const u8 sBw3gSpeciesName_SEALEO[] = _("SEALEO");
static const u8 sBw3gSpeciesName_WALREIN[] = _("WALREIN");
static const u8 sBw3gSpeciesName_SNORUNT[] = _("SNORUNT");
static const u8 sBw3gSpeciesName_GLALIE[] = _("GLALIE");
static const u8 sBw3gSpeciesName_FROSLASS[] = _("FROSLASS");
static const u8 sBw3gSpeciesName_CRYOGONAL[] = _("CRYOGONAL");
static const u8 sBw3gSpeciesName_HORSEA[] = _("HORSEA");
static const u8 sBw3gSpeciesName_SEADRA[] = _("SEADRA");
static const u8 sBw3gSpeciesName_KINGDRA[] = _("KINGDRA");
static const u8 sBw3gSpeciesName_STUNFISK[] = _("STUNFISK");
static const u8 sBw3gSpeciesName_DRATINI[] = _("DRATINI");
static const u8 sBw3gSpeciesName_DRAGONAIR[] = _("DRAGONAIR");
static const u8 sBw3gSpeciesName_DRAGONITE[] = _("DRAGONITE");
static const u8 sBw3gSpeciesName_DEINO[] = _("DEINO");
static const u8 sBw3gSpeciesName_ZWEILOUS[] = _("ZWEILOUS");
static const u8 sBw3gSpeciesName_HYDREIGON[] = _("HYDREIGON");
static const u8 sBw3gSpeciesName_GENESECT[] = _("GENESECT");
static const u8 sBw3gSpeciesName_GENESIS_MON[] = _("G.PROJECT");

const u8 *const gBw3gSpeciesNames[] =
{
    [SPECIES_SNIVY_BW3G] = sBw3gSpeciesName_SNIVY,
    [SPECIES_SERVINE_BW3G] = sBw3gSpeciesName_SERVINE,
    [SPECIES_SERPERIOR_BW3G] = sBw3gSpeciesName_SERPERIOR,
    [SPECIES_TEPIG_BW3G] = sBw3gSpeciesName_TEPIG,
    [SPECIES_PIGNITE_BW3G] = sBw3gSpeciesName_PIGNITE,
    [SPECIES_EMBOAR_BW3G] = sBw3gSpeciesName_EMBOAR,
    [SPECIES_OSHAWOTT_BW3G] = sBw3gSpeciesName_OSHAWOTT,
    [SPECIES_DEWOTT_BW3G] = sBw3gSpeciesName_DEWOTT,
    [SPECIES_SAMUROTT_BW3G] = sBw3gSpeciesName_SAMUROTT,
    [SPECIES_PATRAT_BW3G] = sBw3gSpeciesName_PATRAT,
    [SPECIES_WATCHOG_BW3G] = sBw3gSpeciesName_WATCHOG,
    [SPECIES_PURRLOIN_BW3G] = sBw3gSpeciesName_PURRLOIN,
    [SPECIES_LIEPARD_BW3G] = sBw3gSpeciesName_LIEPARD,
    [SPECIES_PIDOVE_BW3G] = sBw3gSpeciesName_PIDOVE,
    [SPECIES_TRANQUILL_BW3G] = sBw3gSpeciesName_TRANQUILL,
    [SPECIES_UNFEZANT_BW3G] = sBw3gSpeciesName_UNFEZANT,
    [SPECIES_IGGLYBUFF_BW3G] = sBw3gSpeciesName_IGGLYBUFF,
    [SPECIES_JIGGLYPUFF_BW3G] = sBw3gSpeciesName_JIGGLYPUFF,
    [SPECIES_WIGGLYTUFF_BW3G] = sBw3gSpeciesName_WIGGLYTUFF,
    [SPECIES_AZURILL_BW3G] = sBw3gSpeciesName_AZURILL,
    [SPECIES_MARILL_BW3G] = sBw3gSpeciesName_MARILL,
    [SPECIES_AZUMARILL_BW3G] = sBw3gSpeciesName_AZUMARILL,
    [SPECIES_SEWADDLE_BW3G] = sBw3gSpeciesName_SEWADDLE,
    [SPECIES_SWADLOON_BW3G] = sBw3gSpeciesName_SWADLOON,
    [SPECIES_LEAVANNY_BW3G] = sBw3gSpeciesName_LEAVANNY,
    [SPECIES_VENIPEDE_BW3G] = sBw3gSpeciesName_VENIPEDE,
    [SPECIES_WHIRLIPEDE_BW3G] = sBw3gSpeciesName_WHIRLIPEDE,
    [SPECIES_SCOLIPEDE_BW3G] = sBw3gSpeciesName_SCOLIPEDE,
    [SPECIES_LILLIPUP_BW3G] = sBw3gSpeciesName_LILLIPUP,
    [SPECIES_HERDIER_BW3G] = sBw3gSpeciesName_HERDIER,
    [SPECIES_STOUTLAND_BW3G] = sBw3gSpeciesName_STOUTLAND,
    [SPECIES_TYMPOLE_BW3G] = sBw3gSpeciesName_TYMPOLE,
    [SPECIES_PALPITOAD_BW3G] = sBw3gSpeciesName_PALPITOAD,
    [SPECIES_SEISMITOAD_BW3G] = sBw3gSpeciesName_SEISMITOAD,
    [SPECIES_ZUBAT_BW3G] = sBw3gSpeciesName_ZUBAT,
    [SPECIES_GOLBAT_BW3G] = sBw3gSpeciesName_GOLBAT,
    [SPECIES_CROBAT_BW3G] = sBw3gSpeciesName_CROBAT,
    [SPECIES_WOOBAT_BW3G] = sBw3gSpeciesName_WOOBAT,
    [SPECIES_SWOOBAT_BW3G] = sBw3gSpeciesName_SWOOBAT,
    [SPECIES_ROGGENROLA_BW3G] = sBw3gSpeciesName_ROGGENROLA,
    [SPECIES_BOLDORE_BW3G] = sBw3gSpeciesName_BOLDORE,
    [SPECIES_GIGALITH_BW3G] = sBw3gSpeciesName_GIGALITH,
    [SPECIES_CLEFFA_BW3G] = sBw3gSpeciesName_CLEFFA,
    [SPECIES_CLEFAIRY_BW3G] = sBw3gSpeciesName_CLEFAIRY,
    [SPECIES_CLEFABLE_BW3G] = sBw3gSpeciesName_CLEFABLE,
    [SPECIES_MUNNA_BW3G] = sBw3gSpeciesName_MUNNA,
    [SPECIES_MUSHARNA_BW3G] = sBw3gSpeciesName_MUSHARNA,
    [SPECIES_RUFFLET_BW3G] = sBw3gSpeciesName_RUFFLET,
    [SPECIES_BRAVIARY_BW3G] = sBw3gSpeciesName_BRAVIARY,
    [SPECIES_VULLABY_BW3G] = sBw3gSpeciesName_VULLABY,
    [SPECIES_MANDIBUZZ_BW3G] = sBw3gSpeciesName_MANDIBUZZ,
    [SPECIES_BUDEW_BW3G] = sBw3gSpeciesName_BUDEW,
    [SPECIES_ROSELIA_BW3G] = sBw3gSpeciesName_ROSELIA,
    [SPECIES_ROSERADE_BW3G] = sBw3gSpeciesName_ROSERADE,
    [SPECIES_FOONGUS_BW3G] = sBw3gSpeciesName_FOONGUS,
    [SPECIES_AMOONGUSS_BW3G] = sBw3gSpeciesName_AMOONGUSS,
    [SPECIES_RALTS_BW3G] = sBw3gSpeciesName_RALTS,
    [SPECIES_KIRLIA_BW3G] = sBw3gSpeciesName_KIRLIA,
    [SPECIES_GARDEVOIR_BW3G] = sBw3gSpeciesName_GARDEVOIR,
    [SPECIES_GALLADE_BW3G] = sBw3gSpeciesName_GALLADE,
    [SPECIES_BLITZLE_BW3G] = sBw3gSpeciesName_BLITZLE,
    [SPECIES_ZEBSTRIKA_BW3G] = sBw3gSpeciesName_ZEBSTRIKA,
    [SPECIES_MAREEP_BW3G] = sBw3gSpeciesName_MAREEP,
    [SPECIES_FLAAFFY_BW3G] = sBw3gSpeciesName_FLAAFFY,
    [SPECIES_AMPHAROS_BW3G] = sBw3gSpeciesName_AMPHAROS,
    [SPECIES_DRILBUR_BW3G] = sBw3gSpeciesName_DRILBUR,
    [SPECIES_EXCADRILL_BW3G] = sBw3gSpeciesName_EXCADRILL,
    [SPECIES_SNUBBULL_BW3G] = sBw3gSpeciesName_SNUBBULL,
    [SPECIES_GRANBULL_BW3G] = sBw3gSpeciesName_GRANBULL,
    [SPECIES_RIOLU_BW3G] = sBw3gSpeciesName_RIOLU,
    [SPECIES_LUCARIO_BW3G] = sBw3gSpeciesName_LUCARIO,
    [SPECIES_TIMBURR_BW3G] = sBw3gSpeciesName_TIMBURR,
    [SPECIES_GURDURR_BW3G] = sBw3gSpeciesName_GURDURR,
    [SPECIES_CONKELDURR_BW3G] = sBw3gSpeciesName_CONKELDURR,
    [SPECIES_ARON_BW3G] = sBw3gSpeciesName_ARON,
    [SPECIES_LAIRON_BW3G] = sBw3gSpeciesName_LAIRON,
    [SPECIES_AGGRON_BW3G] = sBw3gSpeciesName_AGGRON,
    [SPECIES_ONIX_BW3G] = sBw3gSpeciesName_ONIX,
    [SPECIES_STEELIX_BW3G] = sBw3gSpeciesName_STEELIX,
    [SPECIES_NOSEPASS_BW3G] = sBw3gSpeciesName_NOSEPASS,
    [SPECIES_PROBOPASS_BW3G] = sBw3gSpeciesName_PROBOPASS,
    [SPECIES_MAWILE_BW3G] = sBw3gSpeciesName_MAWILE,
    [SPECIES_DWEBBLE_BW3G] = sBw3gSpeciesName_DWEBBLE,
    [SPECIES_CRUSTLE_BW3G] = sBw3gSpeciesName_CRUSTLE,
    [SPECIES_DRIFLOON_BW3G] = sBw3gSpeciesName_DRIFLOON,
    [SPECIES_DRIFBLIM_BW3G] = sBw3gSpeciesName_DRIFBLIM,
    [SPECIES_MEDITITE_BW3G] = sBw3gSpeciesName_MEDITITE,
    [SPECIES_MEDICHAM_BW3G] = sBw3gSpeciesName_MEDICHAM,
    [SPECIES_HOUNDOUR_BW3G] = sBw3gSpeciesName_HOUNDOUR,
    [SPECIES_HOUNDOOM_BW3G] = sBw3gSpeciesName_HOUNDOOM,
    [SPECIES_YAMASK_BW3G] = sBw3gSpeciesName_YAMASK,
    [SPECIES_COFAGRIGUS_BW3G] = sBw3gSpeciesName_COFAGRIGUS,
    [SPECIES_GASTLY_BW3G] = sBw3gSpeciesName_GASTLY,
    [SPECIES_HAUNTER_BW3G] = sBw3gSpeciesName_HAUNTER,
    [SPECIES_GENGAR_BW3G] = sBw3gSpeciesName_GENGAR,
    [SPECIES_LITWICK_BW3G] = sBw3gSpeciesName_LITWICK,
    [SPECIES_LAMPENT_BW3G] = sBw3gSpeciesName_LAMPENT,
    [SPECIES_CHANDELURE_BW3G] = sBw3gSpeciesName_CHANDELURE,
    [SPECIES_COTTONEE_BW3G] = sBw3gSpeciesName_COTTONEE,
    [SPECIES_WHIMSICOTT_BW3G] = sBw3gSpeciesName_WHIMSICOTT,
    [SPECIES_PETILIL_BW3G] = sBw3gSpeciesName_PETILIL,
    [SPECIES_LILLIGANT_BW3G] = sBw3gSpeciesName_LILLIGANT,
    [SPECIES_YANMA_BW3G] = sBw3gSpeciesName_YANMA,
    [SPECIES_YANMEGA_BW3G] = sBw3gSpeciesName_YANMEGA,
    [SPECIES_SHROOMISH_BW3G] = sBw3gSpeciesName_SHROOMISH,
    [SPECIES_BRELOOM_BW3G] = sBw3gSpeciesName_BRELOOM,
    [SPECIES_JOLTIK_BW3G] = sBw3gSpeciesName_JOLTIK,
    [SPECIES_GALVANTULA_BW3G] = sBw3gSpeciesName_GALVANTULA,
    [SPECIES_SPIRITOMB_BW3G] = sBw3gSpeciesName_SPIRITOMB,
    [SPECIES_ZORUA_BW3G] = sBw3gSpeciesName_ZORUA,
    [SPECIES_ZOROARK_BW3G] = sBw3gSpeciesName_ZOROARK,
    [SPECIES_TRUBBISH_BW3G] = sBw3gSpeciesName_TRUBBISH,
    [SPECIES_GARBODOR_BW3G] = sBw3gSpeciesName_GARBODOR,
    [SPECIES_MAGNEMITE_BW3G] = sBw3gSpeciesName_MAGNEMITE,
    [SPECIES_MAGNETON_BW3G] = sBw3gSpeciesName_MAGNETON,
    [SPECIES_MAGNEZONE_BW3G] = sBw3gSpeciesName_MAGNEZONE,
    [SPECIES_GOTHITA_BW3G] = sBw3gSpeciesName_GOTHITA,
    [SPECIES_GOTHORITA_BW3G] = sBw3gSpeciesName_GOTHORITA,
    [SPECIES_GOTHITELLE_BW3G] = sBw3gSpeciesName_GOTHITELLE,
    [SPECIES_SOLOSIS_BW3G] = sBw3gSpeciesName_SOLOSIS,
    [SPECIES_DUOSION_BW3G] = sBw3gSpeciesName_DUOSION,
    [SPECIES_REUNICLUS_BW3G] = sBw3gSpeciesName_REUNICLUS,
    [SPECIES_DEERLING_BW3G] = sBw3gSpeciesName_DEERLING,
    [SPECIES_SAWSBUCK_BW3G] = sBw3gSpeciesName_SAWSBUCK,
    [SPECIES_KARRABLAST_BW3G] = sBw3gSpeciesName_KARRABLAST,
    [SPECIES_ESCAVALIER_BW3G] = sBw3gSpeciesName_ESCAVALIER,
    [SPECIES_SHELMET_BW3G] = sBw3gSpeciesName_SHELMET,
    [SPECIES_ACCELGOR_BW3G] = sBw3gSpeciesName_ACCELGOR,
    [SPECIES_FERROSEED_BW3G] = sBw3gSpeciesName_FERROSEED,
    [SPECIES_FERROTHORN_BW3G] = sBw3gSpeciesName_FERROTHORN,
    [SPECIES_BASCULIN_BW3G] = sBw3gSpeciesName_BASCULIN,
    [SPECIES_REMORAID_BW3G] = sBw3gSpeciesName_REMORAID,
    [SPECIES_OCTILLERY_BW3G] = sBw3gSpeciesName_OCTILLERY,
    [SPECIES_DARUMAKA_BW3G] = sBw3gSpeciesName_DARUMAKA,
    [SPECIES_DARMANITAN_BW3G] = sBw3gSpeciesName_DARMANITAN,
    [SPECIES_ELEKID_BW3G] = sBw3gSpeciesName_ELEKID,
    [SPECIES_ELECTABUZZ_BW3G] = sBw3gSpeciesName_ELECTABUZZ,
    [SPECIES_ELECTIVIRE_BW3G] = sBw3gSpeciesName_ELECTIVIRE,
    [SPECIES_MAGBY_BW3G] = sBw3gSpeciesName_MAGBY,
    [SPECIES_MAGMAR_BW3G] = sBw3gSpeciesName_MAGMAR,
    [SPECIES_MAGMORTAR_BW3G] = sBw3gSpeciesName_MAGMORTAR,
    [SPECIES_SANDILE_BW3G] = sBw3gSpeciesName_SANDILE,
    [SPECIES_KROKOROK_BW3G] = sBw3gSpeciesName_KROKOROK,
    [SPECIES_KROOKODILE_BW3G] = sBw3gSpeciesName_KROOKODILE,
    [SPECIES_SKORUPI_BW3G] = sBw3gSpeciesName_SKORUPI,
    [SPECIES_DRAPION_BW3G] = sBw3gSpeciesName_DRAPION,
    [SPECIES_TRAPINCH_BW3G] = sBw3gSpeciesName_TRAPINCH,
    [SPECIES_VIBRAVA_BW3G] = sBw3gSpeciesName_VIBRAVA,
    [SPECIES_FLYGON_BW3G] = sBw3gSpeciesName_FLYGON,
    [SPECIES_SCRAGGY_BW3G] = sBw3gSpeciesName_SCRAGGY,
    [SPECIES_SCRAFTY_BW3G] = sBw3gSpeciesName_SCRAFTY,
    [SPECIES_NUMEL_BW3G] = sBw3gSpeciesName_NUMEL,
    [SPECIES_CAMERUPT_BW3G] = sBw3gSpeciesName_CAMERUPT,
    [SPECIES_MARACTUS_BW3G] = sBw3gSpeciesName_MARACTUS,
    [SPECIES_GLIGAR_BW3G] = sBw3gSpeciesName_GLIGAR,
    [SPECIES_GLISCOR_BW3G] = sBw3gSpeciesName_GLISCOR,
    [SPECIES_BALTOY_BW3G] = sBw3gSpeciesName_BALTOY,
    [SPECIES_CLAYDOL_BW3G] = sBw3gSpeciesName_CLAYDOL,
    [SPECIES_SIGILYPH_BW3G] = sBw3gSpeciesName_SIGILYPH,
    [SPECIES_GOLETT_BW3G] = sBw3gSpeciesName_GOLETT,
    [SPECIES_GOLURK_BW3G] = sBw3gSpeciesName_GOLURK,
    [SPECIES_TIRTOUGA_BW3G] = sBw3gSpeciesName_TIRTOUGA,
    [SPECIES_CARRACOSTA_BW3G] = sBw3gSpeciesName_CARRACOSTA,
    [SPECIES_ARCHEN_BW3G] = sBw3gSpeciesName_ARCHEN,
    [SPECIES_ARCHEOPS_BW3G] = sBw3gSpeciesName_ARCHEOPS,
    [SPECIES_FRILLISH_BW3G] = sBw3gSpeciesName_FRILLISH,
    [SPECIES_JELLICENT_BW3G] = sBw3gSpeciesName_JELLICENT,
    [SPECIES_EMOLGA_BW3G] = sBw3gSpeciesName_EMOLGA,
    [SPECIES_VULPIX_BW3G] = sBw3gSpeciesName_VULPIX,
    [SPECIES_NINETALES_BW3G] = sBw3gSpeciesName_NINETALES,
    [SPECIES_DUCKLETT_BW3G] = sBw3gSpeciesName_DUCKLETT,
    [SPECIES_SWANNA_BW3G] = sBw3gSpeciesName_SWANNA,
    [SPECIES_SWABLU_BW3G] = sBw3gSpeciesName_SWABLU,
    [SPECIES_ALTARIA_BW3G] = sBw3gSpeciesName_ALTARIA,
    [SPECIES_AUDINO_BW3G] = sBw3gSpeciesName_AUDINO,
    [SPECIES_EEVEE_BW3G] = sBw3gSpeciesName_EEVEE,
    [SPECIES_VAPOREON_BW3G] = sBw3gSpeciesName_VAPOREON,
    [SPECIES_JOLTEON_BW3G] = sBw3gSpeciesName_JOLTEON,
    [SPECIES_FLAREON_BW3G] = sBw3gSpeciesName_FLAREON,
    [SPECIES_ESPEON_BW3G] = sBw3gSpeciesName_ESPEON,
    [SPECIES_UMBREON_BW3G] = sBw3gSpeciesName_UMBREON,
    [SPECIES_LEAFEON_BW3G] = sBw3gSpeciesName_LEAFEON,
    [SPECIES_GLACEON_BW3G] = sBw3gSpeciesName_GLACEON,
    [SPECIES_SYLVEON_BW3G] = sBw3gSpeciesName_SYLVEON,
    [SPECIES_CROAGUNK_BW3G] = sBw3gSpeciesName_CROAGUNK,
    [SPECIES_TOXICROAK_BW3G] = sBw3gSpeciesName_TOXICROAK,
    [SPECIES_HEATMOR_BW3G] = sBw3gSpeciesName_HEATMOR,
    [SPECIES_DURANT_BW3G] = sBw3gSpeciesName_DURANT,
    [SPECIES_KOFFING_BW3G] = sBw3gSpeciesName_KOFFING,
    [SPECIES_WEEZING_BW3G] = sBw3gSpeciesName_WEEZING,
    [SPECIES_CORSOLA_BW3G] = sBw3gSpeciesName_CORSOLA,
    [SPECIES_PINSIR_BW3G] = sBw3gSpeciesName_PINSIR,
    [SPECIES_HERACROSS_BW3G] = sBw3gSpeciesName_HERACROSS,
    [SPECIES_THROH_BW3G] = sBw3gSpeciesName_THROH,
    [SPECIES_SAWK_BW3G] = sBw3gSpeciesName_SAWK,
    [SPECIES_TROPIUS_BW3G] = sBw3gSpeciesName_TROPIUS,
    [SPECIES_PAWNIARD_BW3G] = sBw3gSpeciesName_PAWNIARD,
    [SPECIES_BISHARP_BW3G] = sBw3gSpeciesName_BISHARP,
    [SPECIES_SKARMORY_BW3G] = sBw3gSpeciesName_SKARMORY,
    [SPECIES_MANTYKE_BW3G] = sBw3gSpeciesName_MANTYKE,
    [SPECIES_MANTINE_BW3G] = sBw3gSpeciesName_MANTINE,
    [SPECIES_AXEW_BW3G] = sBw3gSpeciesName_AXEW,
    [SPECIES_FRAXURE_BW3G] = sBw3gSpeciesName_FRAXURE,
    [SPECIES_HAXORUS_BW3G] = sBw3gSpeciesName_HAXORUS,
    [SPECIES_BOUFFALANT_BW3G] = sBw3gSpeciesName_BOUFFALANT,
    [SPECIES_KLINK_BW3G] = sBw3gSpeciesName_KLINK,
    [SPECIES_KLANG_BW3G] = sBw3gSpeciesName_KLANG,
    [SPECIES_KLINKLANG_BW3G] = sBw3gSpeciesName_KLINKLANG,
    [SPECIES_DITTO_BW3G] = sBw3gSpeciesName_DITTO,
    [SPECIES_STARYU_BW3G] = sBw3gSpeciesName_STARYU,
    [SPECIES_STARMIE_BW3G] = sBw3gSpeciesName_STARMIE,
    [SPECIES_CUBCHOO_BW3G] = sBw3gSpeciesName_CUBCHOO,
    [SPECIES_BEARTIC_BW3G] = sBw3gSpeciesName_BEARTIC,
    [SPECIES_VANILLITE_BW3G] = sBw3gSpeciesName_VANILLITE,
    [SPECIES_VANILLISH_BW3G] = sBw3gSpeciesName_VANILLISH,
    [SPECIES_VANILLUXE_BW3G] = sBw3gSpeciesName_VANILLUXE,
    [SPECIES_SNEASEL_BW3G] = sBw3gSpeciesName_SNEASEL,
    [SPECIES_WEAVILE_BW3G] = sBw3gSpeciesName_WEAVILE,
    [SPECIES_CORPHISH_BW3G] = sBw3gSpeciesName_CORPHISH,
    [SPECIES_CRAWDAUNT_BW3G] = sBw3gSpeciesName_CRAWDAUNT,
    [SPECIES_SWINUB_BW3G] = sBw3gSpeciesName_SWINUB,
    [SPECIES_PILOSWINE_BW3G] = sBw3gSpeciesName_PILOSWINE,
    [SPECIES_MAMOSWINE_BW3G] = sBw3gSpeciesName_MAMOSWINE,
    [SPECIES_LARVITAR_BW3G] = sBw3gSpeciesName_LARVITAR,
    [SPECIES_PUPITAR_BW3G] = sBw3gSpeciesName_PUPITAR,
    [SPECIES_TYRANITAR_BW3G] = sBw3gSpeciesName_TYRANITAR,
    [SPECIES_LARVESTA_BW3G] = sBw3gSpeciesName_LARVESTA,
    [SPECIES_VOLCARONA_BW3G] = sBw3gSpeciesName_VOLCARONA,
    [SPECIES_TYNAMO_BW3G] = sBw3gSpeciesName_TYNAMO,
    [SPECIES_EELEKTRIK_BW3G] = sBw3gSpeciesName_EELEKTRIK,
    [SPECIES_EELEKTROSS_BW3G] = sBw3gSpeciesName_EELEKTROSS,
    [SPECIES_BELDUM_BW3G] = sBw3gSpeciesName_BELDUM,
    [SPECIES_METANG_BW3G] = sBw3gSpeciesName_METANG,
    [SPECIES_METAGROSS_BW3G] = sBw3gSpeciesName_METAGROSS,
    [SPECIES_SPHEAL_BW3G] = sBw3gSpeciesName_SPHEAL,
    [SPECIES_SEALEO_BW3G] = sBw3gSpeciesName_SEALEO,
    [SPECIES_WALREIN_BW3G] = sBw3gSpeciesName_WALREIN,
    [SPECIES_SNORUNT_BW3G] = sBw3gSpeciesName_SNORUNT,
    [SPECIES_GLALIE_BW3G] = sBw3gSpeciesName_GLALIE,
    [SPECIES_FROSLASS_BW3G] = sBw3gSpeciesName_FROSLASS,
    [SPECIES_CRYOGONAL_BW3G] = sBw3gSpeciesName_CRYOGONAL,
    [SPECIES_HORSEA_BW3G] = sBw3gSpeciesName_HORSEA,
    [SPECIES_SEADRA_BW3G] = sBw3gSpeciesName_SEADRA,
    [SPECIES_KINGDRA_BW3G] = sBw3gSpeciesName_KINGDRA,
    [SPECIES_STUNFISK_BW3G] = sBw3gSpeciesName_STUNFISK,
    [SPECIES_DRATINI_BW3G] = sBw3gSpeciesName_DRATINI,
    [SPECIES_DRAGONAIR_BW3G] = sBw3gSpeciesName_DRAGONAIR,
    [SPECIES_DRAGONITE_BW3G] = sBw3gSpeciesName_DRAGONITE,
    [SPECIES_DEINO_BW3G] = sBw3gSpeciesName_DEINO,
    [SPECIES_ZWEILOUS_BW3G] = sBw3gSpeciesName_ZWEILOUS,
    [SPECIES_HYDREIGON_BW3G] = sBw3gSpeciesName_HYDREIGON,
    [SPECIES_GENESECT_BW3G] = sBw3gSpeciesName_GENESECT,
    [SPECIES_GENESIS_MON_BW3G] = sBw3gSpeciesName_GENESIS_MON,
};
